// AUTH TYPES
export const AUTH_TYPES = {
  LOG_OUT: "LOG_OUT",
  AUTHORIZE_USER: "AUTHORIZE_USER",
};

// ASSIST TYPES
export const ASSIST_TYPES = {
  GO_TO_Q2: "GO_TO_Q2",
  JUMP_TO_Q6: "JUMP_TO_Q6",
  GO_TO_Q3: "GO_TO_Q3",
  GO_TO_Q4: "GO_TO_Q4",
  GO_TO_Q5: "GO_TO_Q5",
  GO_TO_Q6: "GO_TO_Q6",
  GO_TO_Q7: "GO_TO_Q7",
  GO_TO_Q8: "GO_TO_Q8",
  GO_TO_FEEDBACK_REPORT: "GO_TO_FEEDBACK_REPORT",
  GO_TO_PREVIOUS: "GO_TO_PREVIOUS",
  SET_ISLOADING_TRUE: "SET_ISLOADING_TRUE",
  SET_ISLOADING_FALSE: "SET_ISLOADING_FALSE",
};

// CONSULT TYPES
export const CONSULT_TYPES = {
  GET_FORMS: "GET_FORMS",
  GET_A_FORM: "GET_A_FORM",
  SUBMIT_FORM: "SUBMIT_FORM",
};
